export {
    Anchor,
    AutoComplete,
    Alert,
    Avatar,
    BackTop,
    Badge,
    Breadcrumb,
    Calendar,
    Card,
    Collapse,
    Carousel,
    Cascader,
    Checkbox,
    Comment,
    ConfigProvider,
    DatePicker,
    Descriptions,
    Divider,
    Dropdown,
    Drawer,
    Empty,
    Form,
    // Icon,
    Input,
    InputNumber,
    // Layout,
    List,
    // LocaleProvider,
    message,
    Menu,
    Mentions,
    Modal,
    Statistic,
    notification,
    PageHeader,
    Pagination,
    Popconfirm,
    Popover,
    Progress,
    Radio,
    Rate,
    Result,
    Select,
    Skeleton,
    Slider,
    Spin,
    Steps,
    Switch,
    Table,
    Transfer,
    Tree,
    TreeSelect,
    Tabs,
    Tag,
    TimePicker,
    Timeline,
    Tooltip,
    Typography,
    Upload,
    version,
    Col,
    Row,
    Image,
  } from 'antd';
  
//   export { Icon } from '@ant-design/compatible';
//   export * from './modalFuns';
//   export * from './notificationFuns';
  // import { Layout } from 'antd';
  // export const Header = Layout.Header;
  